import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import { type Theme, ThemeProvider, ThemedBody } from '@/lib/theme';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Quotes',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialTheme = cookies().get('theme')?.value as Theme | undefined;
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-[100svh]`}>
        <ThemeProvider initialTheme={initialTheme}>
          <Header className="h-16" />
          <ThemedBody>{children}</ThemedBody>
        </ThemeProvider>
      </body>
    </html>
  );
}
